### PR TITLE
First edit

### PR DESCRIPTION
**Pull request by beutlich**

### CODE REVIEW

**Comment by beutlich** [comment]
You need to add @HansOlsson as maintainer first, such that he is able to update this PR.

**Comment by dietmarw** [comment]
Well I wanted first to demonstrate how I can push into HIS PR. But this PR will do fine for demonstration purposes.

**Comment by beutlich** [comment]
OK, thought the question his how HE can update any PR where HE is maintainer.

**Comment by dietmarw** [comment]
Sure but that is what we in the academic world call "being able to apply transfer knowledge" :-D

**Comment by dietmarw** [comment]
Also since you've now done the PR he can do EXACTLY as I will be showing (after haven given him access as maintainer)

**Comment by beutlich** [comment]
Tss, this academia bubble ...

**Pull request closed without merging**
